import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
//types
import { Question, QuestionMode } from '../../types/question'
// components
import CreateQuestionList from '../../components/CreateQuestionList'
import CreateQuestionModal from '../../components/CreateQuestionModal'
// ui components
import { Container } from '@mui/material'
// utils
import generateUniqueId from '../../utils/id-generator'

const tempQuestions: Question[] = [
  {
    id: 'welcome_page',
    title: 'صفحه خوش‌آمدگویی',
    mode: QuestionMode.Info,
  },
  {
    id: generateUniqueId(8),
    title: 'سوال اول',
    mode: QuestionMode.Text,
  },
  {
    id: generateUniqueId(8),
    title: 'سوال دوم',
    mode: QuestionMode.Text,
  },
  {
    id: generateUniqueId(8),
    title: 'سوال سوم',
    mode: QuestionMode.Text,
  },
  {
    id: 'end_page',
    title: 'دانکا!',
    mode: QuestionMode.Info,
  },
]

const getModalData = (id: string) => {
  const index = tempQuestions.findIndex((item) => item.id === id)
  return tempQuestions[index]
}

const Home: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false)
  const [isNew, setIsNew] = useState<boolean>(false)
  const [modalData, setModalData] = useState<Question | null>(null)

  const handleItemClick = (id: string) => {
    setIsNew(false)
    setIsModalOpen(true)
    const data: Question = getModalData(id)
    setModalData(data)
  }
  const handleNewClick = () => {
    setIsNew(true)
    setIsModalOpen(true)
    setModalData(null)
  }

  const handleModalClose = ({ save }: { save: boolean }) => {
    setIsModalOpen(false)
    if (save) alert('gonna save that')
    setModalData(null)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="sm" sx={{ py: 4 }}>
        <CreateQuestionModal
          isOpen={isModalOpen}
          isNew={isNew}
          data={modalData}
          onClose={handleModalClose}
        />
        <CreateQuestionList
          items={tempQuestions}
          onItemClick={handleItemClick}
          onNewClick={handleNewClick}
        />
      </Container>
    </div>
  )
}

export default Home
